# This is a basic workflow to help you get started with Actions

name: CI-feature-branch

# Controls when the action will run.
on:
  # Triggers the workflow on push to feature branches
  push:
    branches: ["*", "!main", "!master", "!skip/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Install dependencies
        run: |
          lerna bootstrap

      - name: Test
        run: |
          lerna run test

#      - name: Install backend
#        working-directory: backend
#        run: |
#          npm install
#
#      - name: Build
#        run: |
#          npm run build
#
#      - name: Build frontend
#        working-directory: frontend
#        run: |
#          npm run build
#
#      - name: Build backend
#        working-directory: backend
#        run: |
#          npm run build
#
#      - name: Test
#        run: |
#          npm run test -- test
#
#      - name: Test frontend
#        working-directory: frontend
#        run: |
#          npm test
#
#      - name: Identify dev account and region
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: "us-east-1"
#        run: |
#          aws sts get-caller-identity
#          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'
#
#      - name: Deploy the webapp stack to the dev account
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: "us-east-1"
#        run: |
#          npx cdk bootstrap
#          STACKNAME=$(npx @cdk-turnkey/stackname@1.2.0 --suffix webapp)
#          npx cdk deploy --require-approval never ${STACKNAME}
#
#      - name: Deploy to the frontend bucket (dev account)
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: "us-east-1"
#        run: |
#          bash scripts/deploy-frontend.sh
