name: CI-feature-branch

on:
  push:
    branches-ignore: 
      - "main"
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Get yarn cache directory path ğŸ”
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Use yarn cache ğŸ“¦
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install and Build ğŸ”§
        run: |
          yarn install
          yarn workspaces run build
      
      - name: Upload Artifact ğŸ“‚
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./
      
  deploy-to-dev:
    name: Deploy to Dev Acount
    runs-on: ubuntu-latest
    needs: 
      - build
    
    steps:
      - name: Download Artifact ğŸ“‚
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
    
      - name: Identify account and region ğŸ”
        working-directory: packages/cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'

      - name: Deploy the webapp stack ğŸš€
        working-directory: packages/cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npx cdk bootstrap
          STACKNAME=$(npx @cdk-turnkey/stackname@1.2.0 --suffix webapp)
          npx cdk deploy --require-approval never ${STACKNAME}

      - name: Publish to frontend bucket ğŸ‰
        working-directory: packages/cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          bash scripts/deploy-frontend.sh
